language: go
go:
  - 1.4
  - tip
before_install:
 - echo "yes" | sudo add-apt-repository ppa:travis-ci/sqlite3
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsqlite3-dev
install:
- go get github.com/gwenn/yacr
- go get -tags all github.com/gwenn/gosqlite
before_script:
 - go get github.com/bmizerany/assert
script:
 - go test -v -tags all github.com/gwenn/gosqlite